@MinecraftPlaylistBuilderApp.Server_HostAddress = https://localhost:7258

GET {{MinecraftPlaylistBuilderApp.Server_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{MinecraftPlaylistBuilderApp.Server_HostAddress}}/api/series/
Accept: application/json

###

GET {{MinecraftPlaylistBuilderApp.Server_HostAddress}}/api/series/herMitcraft/seasons
Accept: application/json

###

GET {{MinecraftPlaylistBuilderApp.Server_HostAddress}}/api/series/hermitcraft/seasons
Accept: application/json